apiVersion: v1
kind: Secret
namespace: {{ .Values.global.namespace }}
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  config.yaml: |-
    mongodbConn: {{ .Values.config.mongodbConn }}
    rabbitMQConn: {{ .Values.config.rabbitMQConn }}
    taskQueueName: {{ .Values.config.taskQueueName }}
    port: {{ .Values.config.port }}
    SMTPServer: {{ .Values.config.SMTPServer }}
    SMTPPort:  {{ .Values.config.SMTPPort }}
    SMTPEmail:  {{ .Values.config.SMTPEmail }}
    SMTPPassword:  {{ .Values.config.SMTPPassword }}
    ops: {{ .Values.config.ops }}
    passphrase: {{ (randAlphaNum 16) | quote }}
    jwtTokenSecret: {{ (randAlphaNum 16) | quote }}
    adminUsername: {{ .Values.config.adminUsername }}
    adminPassword: {{ .Values.config.adminPassword }}

---