mongodbConn: mongodb://localhost:27017
rabbitMQConn: "amqp://guest:guest@localhost:5672/"
taskQueueName: "whitelist.request.queue"
port: ":8080"
SMTPServer: ""
SMTPPort: 587
SMTPEmail: ""
SMTPPassword: ""
ops: ["op1@gmail.com"]
passphrase: "passphrase"
jwtTokenSecret: "jwttokensecret"
adminUsername: "testadmin"
adminPassword: "testadminpassword"
dispatchingStrategy: "Broadcast"
recaptchaPrivateKey: ""
