mongodbConn: mongodb://localhost:27017
rabbitMQConn: amqp://guest:guest@localhost:5672/
taskQueueName: "whitelist.request.queue"
port: ":8080"
SMTPServer: "smtp.mailgun.org"
SMTPPort: 587
SMTPEmail: "postmaster@sandboxe28c081ade7c4188a38869f685116d69.mailgun.org"
SMTPPassword: "d41c03f91bd72dae6d9cd7929f94d6b3"
ops: ["tiaven1104@gmail.com"]
passphrase: "bwxqx123"