replicas: 1
image:
  registry: us.gcr.io/mc-whitelist-demo/mc-whitelist-app
  tag: feed1e8
# ingress:
#   certificate:  mc-whitelist-ingress-certificate
#   static_ip: mc-whitelist-frontend-ingress-ip

#*sitekey for your recaptcha. Set up here Set up https://www.google.com/recaptcha/intro/v3.html. [Use V2 Invisible Version]
recaptcha_sitekey: 6Ld7qcAUAAAAADtzQrmz7it_EOpygwqSKuC8nY5I